/**
 * Curated national scholarship database seed — 55 scholarships across:
 * - First-gen specific
 * - STEM & Engineering (including civil/construction engineering)
 * - Income-based / need-based
 * - Underrepresented groups
 * - State-agnostic general
 * - Career-pathway specific (construction, surveying, engineering tech)
 */
export const SEED_SCHOLARSHIPS = [
	// ── First-Gen Focused ────────────────────────────────────────────
	{
		name: "Gates Scholarship",
		description:
			"Full cost-of-attendance scholarship for exceptional, Pell-eligible minority students pursuing STEM, education, library science, or public service.",
		amount: null,
		amountMin: 10_000,
		amountMax: 50_000,
		deadlineText: "September 15 annually",
		deadlineMonth: 9,
		deadlineDay: 15,
		minGpa: 3.3,
		requiresFirstGen: true,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["black", "hispanic", "asian", "native_american"]),
		applicationUrl: "https://www.thegatesscholarship.org",
		renewable: true,
	},
	{
		name: "Dell Scholars Program",
		description:
			"Need-based scholarship for students from low-income backgrounds who demonstrate the ability to succeed with minimal support.",
		amount: 20_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "December 1 annually",
		deadlineMonth: 12,
		deadlineDay: 1,
		minGpa: 2.4,
		requiresFirstGen: true,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["low_income"]),
		applicationUrl: "https://www.dellscholars.org",
		renewable: true,
	},
	{
		name: "QuestBridge National College Match",
		description:
			"Connects high-achieving, low-income students with full four-year scholarships at elite partner colleges.",
		amount: null,
		amountMin: 40_000,
		amountMax: 80_000,
		deadlineText: "September 26 annually",
		deadlineMonth: 9,
		deadlineDay: 26,
		minGpa: 3.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["low_income"]),
		applicationUrl: "https://www.questbridge.org",
		renewable: true,
	},
	{
		name: "Jack Kent Cooke Foundation Undergraduate Transfer Scholarship",
		description:
			"Supports high-achieving community college students with financial need who are transferring to four-year institutions.",
		amount: 40_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "January 10 annually",
		deadlineMonth: 1,
		deadlineDay: 10,
		minGpa: 3.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["low_income", "transfer_student"]),
		applicationUrl: "https://www.jkcf.org/our-scholarships/undergraduate-transfer-scholarship",
		renewable: true,
	},
	{
		name: "Horatio Alger National Scholarship",
		description:
			"For students who have overcome adversity and demonstrated ambition, strength of character, and financial need.",
		amount: 25_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "October 25 annually",
		deadlineMonth: 10,
		deadlineDay: 25,
		minGpa: 2.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["low_income"]),
		applicationUrl:
			"https://scholars.horatioalger.org/scholarships/about-our-scholarship-programs/",
		renewable: false,
	},
	{
		name: "Burger King Scholars Program",
		description:
			"Scholarships for employees, spouses/domestic partners, and high school seniors based on work experience and academic performance.",
		amount: 1_000,
		amountMin: 1_000,
		amountMax: 50_000,
		deadlineText: "December 15 annually",
		deadlineMonth: 12,
		deadlineDay: 15,
		minGpa: 2.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.burgerkingscholarshipfund.org",
		renewable: false,
	},

	// ── STEM & Engineering ────────────────────────────────────────────
	{
		name: "Society of Women Engineers Scholarship",
		description:
			"Multiple scholarships for women pursuing ABET-accredited engineering or computer science programs.",
		amount: null,
		amountMin: 1_000,
		amountMax: 15_000,
		deadlineText: "February 15 annually",
		deadlineMonth: 2,
		deadlineDay: 15,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Engineering",
			"Civil Engineering",
			"Computer Science",
			"Mechanical Engineering",
			"Electrical Engineering",
		]),
		demographicTags: JSON.stringify(["female"]),
		applicationUrl: "https://scholarships.swe.org",
		renewable: true,
	},
	{
		name: "ASCE (American Society of Civil Engineers) Scholarship",
		description:
			"Multiple scholarships for students pursuing undergraduate civil engineering degrees.",
		amount: null,
		amountMin: 2_500,
		amountMax: 10_000,
		deadlineText: "February 10 annually",
		deadlineMonth: 2,
		deadlineDay: 10,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify(["Civil Engineering", "Engineering Technology"]),
		demographicTags: null,
		applicationUrl: "https://www.asce.org/career-growth/scholarships",
		renewable: false,
	},
	{
		name: "AGC Education and Research Foundation Scholarship",
		description:
			"For students pursuing construction management, civil engineering, or building construction degrees.",
		amount: 2_500,
		amountMin: null,
		amountMax: null,
		deadlineText: "November 1 annually",
		deadlineMonth: 11,
		deadlineDay: 1,
		minGpa: 2.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Construction Management",
			"Civil Engineering",
			"Building Technology",
			"Engineering Technology",
			"Construction Engineering",
		]),
		demographicTags: null,
		applicationUrl: "https://www.agcfoundation.org/programs/scholarships",
		renewable: true,
	},
	{
		name: "NSPE (National Society of Professional Engineers) Scholarships",
		description: "Scholarships for engineering students committed to the profession.",
		amount: null,
		amountMin: 1_000,
		amountMax: 10_000,
		deadlineText: "March 1 annually",
		deadlineMonth: 3,
		deadlineDay: 1,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Engineering",
			"Civil Engineering",
			"Mechanical Engineering",
			"Electrical Engineering",
		]),
		demographicTags: null,
		applicationUrl: "https://www.nspe.org/resources/students/scholarships",
		renewable: false,
	},
	{
		name: "ACEC (American Council of Engineering Companies) Scholarship",
		description:
			"For engineering and land surveying students pursuing careers in the private sector.",
		amount: 5_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "February 28 annually",
		deadlineMonth: 2,
		deadlineDay: 28,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Civil Engineering",
			"Land Surveying",
			"Engineering Technology",
			"Surveying",
		]),
		demographicTags: null,
		applicationUrl: "https://www.acec.org/education-events/scholarships/",
		renewable: false,
	},
	{
		name: "NSPS (National Society of Professional Surveyors) Scholarship",
		description:
			"Dedicated scholarships for students pursuing surveying, geomatics, or mapping science.",
		amount: null,
		amountMin: 1_000,
		amountMax: 3_000,
		deadlineText: "January 21 annually",
		deadlineMonth: 1,
		deadlineDay: 21,
		minGpa: 2.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Surveying",
			"Geomatics",
			"Land Surveying",
			"Civil Engineering",
		]),
		demographicTags: null,
		applicationUrl: "https://www.nsps.us.com/page/Scholarships",
		renewable: false,
	},
	{
		name: "Associated Builders and Contractors Scholarship",
		description:
			"For students in construction-related degree programs who plan careers in the merit shop construction industry.",
		amount: null,
		amountMin: 1_000,
		amountMax: 5_000,
		deadlineText: "March 15 annually",
		deadlineMonth: 3,
		deadlineDay: 15,
		minGpa: 2.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Construction Management",
			"Building Technology",
			"Engineering Technology",
			"Building Construction Technology",
		]),
		demographicTags: null,
		applicationUrl: "https://www.abc.org/Education-Training/Scholarships",
		renewable: false,
	},
	{
		name: "CMAA (Construction Management Association of America) Scholarship",
		description: "For students pursuing construction management as a career.",
		amount: 5_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "April 1 annually",
		deadlineMonth: 4,
		deadlineDay: 1,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Construction Management",
			"Building Technology",
			"Civil Engineering",
		]),
		demographicTags: null,
		applicationUrl: "https://www.cmaanet.org/foundation/scholarships",
		renewable: false,
	},
	{
		name: "Regeneron Science Talent Search",
		description:
			"Prestigious STEM research competition for high school seniors with original research projects.",
		amount: null,
		amountMin: 2_000,
		amountMax: 250_000,
		deadlineText: "November 13 annually",
		deadlineMonth: 11,
		deadlineDay: 13,
		minGpa: 3.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify(["STEM", "Science", "Engineering", "Math"]),
		demographicTags: null,
		applicationUrl: "https://www.societyforscience.org/regeneron-sts/",
		renewable: false,
	},
	{
		name: "BEYA STEM Conference Scholarships",
		description:
			"Scholarships for Black students pursuing STEM fields at accredited four-year institutions.",
		amount: null,
		amountMin: 2_000,
		amountMax: 10_000,
		deadlineText: "October 1 annually",
		deadlineMonth: 10,
		deadlineDay: 1,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify(["Engineering", "STEM", "Computer Science"]),
		demographicTags: JSON.stringify(["black"]),
		applicationUrl: "https://www.beya-stem.com",
		renewable: false,
	},

	// ── Underrepresented Groups ──────────────────────────────────────
	{
		name: "Hispanic Scholarship Fund",
		description:
			"Scholarships for Hispanic/Latino students pursuing undergraduate and graduate degrees.",
		amount: null,
		amountMin: 500,
		amountMax: 5_000,
		deadlineText: "February 15 annually",
		deadlineMonth: 2,
		deadlineDay: 15,
		minGpa: 2.5,
		requiresFirstGen: false,
		requiresEssay: false,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["hispanic"]),
		applicationUrl: "https://www.hsf.net/scholarship",
		renewable: true,
	},
	{
		name: "UNCF (United Negro College Fund) Scholarships",
		description:
			"Numerous scholarships for Black/African American students at HBCUs and other institutions.",
		amount: null,
		amountMin: 2_000,
		amountMax: 5_000,
		deadlineText: "Rolling deadline, varies by program",
		deadlineMonth: null,
		deadlineDay: null,
		minGpa: 2.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["black"]),
		applicationUrl: "https://www.uncf.org/scholarships",
		renewable: false,
	},
	{
		name: "AAUW (American Association of University Women) Scholarship",
		description:
			"Financial aid for women pursuing degrees in fields where women are underrepresented, including STEM.",
		amount: null,
		amountMin: 2_000,
		amountMax: 12_000,
		deadlineText: "November 15 annually",
		deadlineMonth: 11,
		deadlineDay: 15,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["female"]),
		applicationUrl: "https://www.aauw.org/resources/programs/fellowships-grants/",
		renewable: false,
	},
	{
		name: "Asian Pacific Community Fund Scholarship",
		description:
			"Scholarships for students of Asian and Pacific Islander descent demonstrating academic achievement and community involvement.",
		amount: null,
		amountMin: 2_500,
		amountMax: 5_000,
		deadlineText: "March 1 annually",
		deadlineMonth: 3,
		deadlineDay: 1,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["asian", "pacific_islander"]),
		applicationUrl: "https://apcf.org/scholarship/",
		renewable: false,
	},
	{
		name: "American Indian College Fund Full Circle Scholarship",
		description:
			"Scholarships for American Indian and Alaska Native students attending tribal colleges.",
		amount: null,
		amountMin: 500,
		amountMax: 5_000,
		deadlineText: "May 31 annually",
		deadlineMonth: 5,
		deadlineDay: 31,
		minGpa: 2.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["native_american"]),
		applicationUrl: "https://collegefund.org/students/scholarships/",
		renewable: true,
	},

	// ── Need-Based / Income-Based ─────────────────────────────────────
	{
		name: "Coca-Cola Scholars Program",
		description:
			"Merit-based scholarship for high school seniors with exceptional achievements in academics, leadership, and community.",
		amount: 20_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "October 31 annually",
		deadlineMonth: 10,
		deadlineDay: 31,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.coca-colascholarsfoundation.org",
		renewable: false,
	},
	{
		name: "Elks National Foundation Most Valuable Student Scholarship",
		description: "Merit-based scholarship open to all graduating high school seniors.",
		amount: null,
		amountMin: 4_000,
		amountMax: 50_000,
		deadlineText: "November 5 annually",
		deadlineMonth: 11,
		deadlineDay: 5,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.elks.org/scholars/scholarships/mvs.cfm",
		renewable: true,
	},
	{
		name: "Prudential Spirit of Community Award",
		description:
			"Recognizes middle and high school students for volunteer service. Includes scholarship component.",
		amount: 1_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "November 1 annually",
		deadlineMonth: 11,
		deadlineDay: 1,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://spirit.prudential.com",
		renewable: false,
	},
	{
		name: "AXA Achievement Scholarship",
		description:
			"Non-need-based scholarship for students who have demonstrated ambition and achievement.",
		amount: 10_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "December 15 annually",
		deadlineMonth: 12,
		deadlineDay: 15,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://us.axa.com/axa-foundation/scholarship.html",
		renewable: false,
	},
	{
		name: "Scholarship America Dream Award",
		description:
			"Scholarships for students with significant financial need who have overcome barriers in their pursuit of higher education.",
		amount: 15_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "April 15 annually",
		deadlineMonth: 4,
		deadlineDay: 15,
		minGpa: 3.0,
		requiresFirstGen: true,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["low_income"]),
		applicationUrl: "https://scholarshipamerica.org/dream-award/",
		renewable: true,
	},
	{
		name: "Sallie Mae Scholarship",
		description:
			"Need-based scholarships for undergraduate students. Multiple award levels available.",
		amount: null,
		amountMin: 1_000,
		amountMax: 5_000,
		deadlineText: "April 30 annually",
		deadlineMonth: 4,
		deadlineDay: 30,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: false,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["low_income"]),
		applicationUrl: "https://www.salliemae.com/college-planning/scholarship-search/",
		renewable: false,
	},

	// ── Florida-specific (Valencia region example) ───────────────────
	{
		name: "Bright Futures Scholarship (Florida)",
		description:
			"Florida's merit-based scholarship program for Florida high school graduates. Covers a portion of tuition at Florida colleges.",
		amount: null,
		amountMin: 3_000,
		amountMax: 6_000,
		deadlineText: "August 31 annually (after high school graduation)",
		deadlineMonth: 8,
		deadlineDay: 31,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: false,
		eligibleStates: JSON.stringify(["FL"]),
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.floridastudentfinancialaidsg.org/SAPHome/SAPHome?url=home",
		renewable: true,
	},
	{
		name: "Valencia College Foundation Scholarship",
		description:
			"Numerous institutional scholarships for Valencia College students, including need and merit-based awards.",
		amount: null,
		amountMin: 500,
		amountMax: 4_000,
		deadlineText: "April 1 annually",
		deadlineMonth: 4,
		deadlineDay: 1,
		minGpa: 2.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: JSON.stringify(["FL"]),
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://valenciacollege.edu/financial-aid/scholarships/",
		renewable: true,
	},

	// ── Military / ROTC / Service ────────────────────────────────────
	{
		name: "Army ROTC Scholarship",
		description:
			"Covers full tuition, fees, and provides stipends for students who commit to Army service.",
		amount: null,
		amountMin: 10_000,
		amountMax: 40_000,
		deadlineText: "February 1 for 4-year scholarships",
		deadlineMonth: 2,
		deadlineDay: 1,
		minGpa: 2.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.goarmy.com/rotc/scholarships.html",
		renewable: true,
	},
	{
		name: "Navy ROTC Scholarship",
		description:
			"Full scholarships for students who commit to serve as Navy or Marine Corps officers.",
		amount: null,
		amountMin: 10_000,
		amountMax: 40_000,
		deadlineText: "January 31 annually",
		deadlineMonth: 1,
		deadlineDay: 31,
		minGpa: 3.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.nrotc.navy.mil/scholarships.html",
		renewable: true,
	},

	// ── Essay-free / Auto-applied ────────────────────────────────────
	{
		name: "Niche No Essay Scholarship",
		description:
			"Monthly scholarship drawing. No essay required — just complete your Niche profile.",
		amount: 2_500,
		amountMin: null,
		amountMax: null,
		deadlineText: "Monthly rolling deadline (last day of each month)",
		deadlineMonth: null,
		deadlineDay: null,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: false,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.niche.com/colleges/scholarships/no-essay-scholarship/",
		renewable: false,
	},
	{
		name: "Fastweb Easy Scholarships",
		description: "Curated list of scholarships with minimal requirements on Fastweb's database.",
		amount: null,
		amountMin: 500,
		amountMax: 5_000,
		deadlineText: "Rolling deadline, varies by scholarship",
		deadlineMonth: null,
		deadlineDay: null,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: false,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.fastweb.com",
		renewable: false,
	},
	{
		name: "Scholarships.com Free Scholarship Search",
		description:
			"Access to scholarship database matched to your profile. Many no-essay options available.",
		amount: null,
		amountMin: 500,
		amountMax: 10_000,
		deadlineText: "Rolling deadline, varies by scholarship",
		deadlineMonth: null,
		deadlineDay: null,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: false,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.scholarships.com",
		renewable: false,
	},

	// ── Construction / Skilled Trades ─────────────────────────────────
	{
		name: "Home Builders Institute (HBI) Skilled Trades Scholarship",
		description: "For students pursuing careers in residential construction and skilled trades.",
		amount: null,
		amountMin: 1_000,
		amountMax: 5_000,
		deadlineText: "March 31 annually",
		deadlineMonth: 3,
		deadlineDay: 31,
		minGpa: 2.0,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Building Construction Technology",
			"Construction Management",
			"Engineering Technology",
			"Skilled Trades",
		]),
		demographicTags: null,
		applicationUrl: "https://hbi.org",
		renewable: false,
	},
	{
		name: "NAHB Scholarship Foundation",
		description:
			"National Association of Home Builders scholarships for students in construction-related programs.",
		amount: 1_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "April 15 annually",
		deadlineMonth: 4,
		deadlineDay: 15,
		minGpa: 2.5,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: JSON.stringify([
			"Construction Management",
			"Building Technology",
			"Engineering Technology",
			"Building Construction Technology",
		]),
		demographicTags: null,
		applicationUrl: "https://www.nahb.org/education-and-events/scholarships",
		renewable: false,
	},

	// ── General Merit / Additional ────────────────────────────────────
	{
		name: "College Board Opportunity Scholarships",
		description:
			"Scholarships for students who complete college planning steps through the College Board platform.",
		amount: null,
		amountMin: 500,
		amountMax: 40_000,
		deadlineText: "Rolling deadline throughout the year",
		deadlineMonth: null,
		deadlineDay: null,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: false,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://opportunityscholarships.collegeboard.org",
		renewable: false,
	},
	{
		name: "Common App Fee Waiver + Scholarship Access",
		description:
			"Fee waivers and scholarship referrals for students who qualify based on financial need.",
		amount: null,
		amountMin: 100,
		amountMax: 2_000,
		deadlineText: "Rolling deadline — apply during Common App completion",
		deadlineMonth: null,
		deadlineDay: null,
		minGpa: null,
		requiresFirstGen: true,
		requiresEssay: false,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["low_income"]),
		applicationUrl: "https://www.commonapp.org/blog/demystifying-common-app-fee-waiver",
		renewable: false,
	},
	{
		name: "Ron Brown Scholar Program",
		description:
			"For African American students demonstrating academic excellence, leadership, and community service.",
		amount: 10_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "January 9 annually",
		deadlineMonth: 1,
		deadlineDay: 9,
		minGpa: null,
		requiresFirstGen: false,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: JSON.stringify(["black"]),
		applicationUrl: "https://www.ronbrown.org",
		renewable: true,
	},
	{
		name: "First-Generation College Students Scholarship (Sallie Mae)",
		description: "Specifically for students who are the first in their family to attend college.",
		amount: 5_000,
		amountMin: null,
		amountMax: null,
		deadlineText: "April 30 annually",
		deadlineMonth: 4,
		deadlineDay: 30,
		minGpa: null,
		requiresFirstGen: true,
		requiresEssay: true,
		eligibleStates: null,
		eligibleMajors: null,
		demographicTags: null,
		applicationUrl: "https://www.salliemae.com/college-planning/scholarship-search/",
		renewable: false,
	},
] as const;
